name: my_parking
description: "간편한 주차장 이용을 위한 스마트 주차앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  dio: ^5.0.0
  go_router: ^13.1.0
  equatable: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner:
  freezed:
  json_serializable:

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
