name: F-Lab SonarCloud Code Analyze

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CACHED_DEPENDENCIES_PATHS: '**/node_modules'

jobs:
  CodeAnalyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set SonarCloud Project Key
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          SONAR_PROJECT_KEY="${ORG_NAME}_${REPO_NAME}"
          echo "SONAR_PROJECT_KEY=$SONAR_PROJECT_KEY" >> $GITHUB_ENV 

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        id: analyze-sonarcloud
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_BOT }}
          SONAR_TOKEN: ${{ secrets.SECRET_SONARQUBE }}
        with:
          args:
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=f-lab-edu-1

      # key.properties 파일 생성 (api key 정보 보관)
      - name: Creating key.properties file
        env:
          PROPERTIES_PATH: "./key.properties"
        run: |
          echo keyPassword=\${{ secrets.NAVER_API_KEY }} > ${{env.NAVER_API_KEY}}
          echo storePassword=\${{ secrets.PARKING_API_KEY }} >> ${{env.PARKING_API_KEY}}

      # 의존성 설치
      - name: Install dependencies
        run: flutter pub get

      # 코드 제너레이션 (ex. freezed)
      - name: Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # 코드 분석
      - name: Analyze code
        run: flutter analyze

      # 테스트 진행
      - name: Run tests
        run: flutter test --coverage

      # 코드 커버리지 수치 기록
      - name: Upload code coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov.info
